USE [QLDSV_TC]
GO
/****** Object:  StoredProcedure [dbo].[sp_InDSLTC]    Script Date: 14/12/2021 4:37:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[sp_InDSLTC] @NIENKHOA nchar(9), @HOCKY int
AS
BEGIN

	SELECT  ROW_NUMBER() over(ORDER BY mh.TENMH, ltc.NHOM) STT, mh.TENMH, ltc.NHOM, (gv.HO + ' ' + gv.TEN) as 'HO TEN', ltc.SOSVTOITHIEU, COUNT(dk.MASV) as soSVDK
	
	FROM  (SELECT ltc.MALTC, ltc.NIENKHOA, ltc.HOCKY, ltc.nhom, ltc.SOSVTOITHIEU , ltc.MAGV , ltc.MAMH , ltc.HUYLOP FROM LOPTINCHI as ltc WHERE ltc.NIENKHOA = @NIENKHOA AND ltc.HOCKY = @HOCKY AND ltc.HUYLOP = 0) as ltc

	LEFT JOIN GIANGVIEN as gv ON gv.MAGV = ltc.MAGV
	LEFT JOIN MONHOC as mh ON mh.MAMH = ltc.MAMH
	LEFT JOIN DANGKY as dk ON dk.MALTC = ltc.MALTC

	GROUP BY ltc.NHOM, mh.TENMH, gv.HO, gv.TEN, ltc.SOSVTOITHIEU
	ORDER BY mh.TENMH, ltc.NHOM
	  
END
