USE [QLDSV_TC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROC [dbo].[sp_KiemTraMaMH]
@MAMH char(15)
AS
BEGIN
	IF EXISTS ( SELECT * FROM MONHOC WHERE MONHOC.MAMH = @MAMH)
	BEGIN
		RAISERROR ('Mã môn học đã tồn tại', 16,1)
		RETURN 1;
	END

	IF EXISTS ( SELECT * FROM LINK1.QLDSV_TC.DBO.MONHOC WHERE MONHOC.MAMH = @MAMH)
	BEGIN
		RAISERROR ('Mã môn học đã tồn tại trên chi nhánh khác', 16,2)
		RETURN 1;
	END

	IF EXISTS ( SELECT * FROM LINK0.QLDSV_TC.DBO.MONHOC WHERE MONHOC.MAMH = @MAMH)
	BEGIN
		RAISERROR ('Mã môn học đã tồn tại trên chi nhánh khác', 16,3)
		RETURN 1;
	END

RETURN 0;
END