USE [QLDSV_TC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROC [dbo].[sp_KiemTraMaLop]
@MALOP char(10)
AS
BEGIN
	IF EXISTS ( SELECT * FROM LOP WHERE LOP.MALOP = @MALOP)
	BEGIN
		RAISERROR ('Mã lớp học đã tồn tại', 16,1)
		RETURN 1;
	END

	IF EXISTS ( SELECT * FROM LINK1.QLDSV_TC.DBO.LOP WHERE LOP.MALOP = @MALOP)
	BEGIN
		RAISERROR ('Mã lớp học đã tồn tại trên chi nhánh khác', 16,1)
		RETURN 1;
	END

	IF EXISTS ( SELECT * FROM LINK0.QLDSV_TC.DBO.LOP WHERE LOP.MALOP = @MALOP)
	BEGIN
		RAISERROR ('Mã lớp học đã tồn tại trên chi nhánh khác', 16,1)
		RETURN 1;
	END

RETURN 0;
END