USE [QLDSV_TC]
GO
/****** Object:  StoredProcedure [dbo].[sp_SuaChiTietDongHP]    Script Date: 12/10/2021 7:25:02 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE OR ALTER   PROCEDURE [dbo].[sp_SuaChiTietDongHP]
	-- khai bao cac bien tam 
	@MASV nchar(10), 
	@NIENKHOA nchar(9), @HOCKY int,  @NGAYDONG date,
	@NIENKHOANEW nchar(9), @HOCKYNEW  int, @SOTIENDONGNEW int, @NGAYDONGNEW date
AS
BEGIN

	DECLARE @TONGTIENDADONG int
	DECLARE @HOCPHI int

	SET XACT_ABORT ON

	BEGIN TRY
		BEGIN DISTRIBUTED TRANSACTION

		UPDATE CT_DONGHOCPHI
		SET NGAYDONG = @NGAYDONGNEW, SOTIENDONG = @SOTIENDONGNEW
		WHERE MASV = @MASV AND NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND NGAYDONG = @NGAYDONG
		

		SELECT @HOCPHI = HP.HOCPHI, @TONGTIENDADONG = ISNULL(CT.SOTIENDADONG, 0)
		FROM (SELECT NIENKHOA, HOCKY, HOCPHI, MASV FROM HOCPHI WHERE MASV = @MASV) as HP
		LEFT JOIN (
					SELECT MASV, NIENKHOA, HOCKY, SUM(SOTIENDONG) AS SOTIENDADONG 
					FROM CT_DONGHOCPHI GROUP BY NIENKHOA, HOCKY, MASV
				) AS CT
		ON HP.MASV = CT.MASV AND CT.NIENKHOA = HP.NIENKHOA AND CT.HOCKY = HP.HOCKY

		
		SELECT @TONGTIENDADONG = SUM(SOTIENDONG)
		FROM CT_DONGHOCPHI CT
		WHERE CT.MASV = @MASV AND CT.NIENKHOA = @NIENKHOA AND CT.HOCKY = @HOCKY 
	END TRY

	BEGIN CATCH
		IF (@@TRANCOUNT > 0)
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR ('Lỗi hệ thống!', 16,2)
			RETURN -1;
		END
	END CATCH
	  
	IF(@TONGTIENDADONG > @HOCPHI)
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR ('Số tiền cần sửa vượt quá tiền học phí. Ko thể cập nhật!', 16,1)
		RETURN 1;
	END

	IF(@@TRANCOUNT > 0)
	BEGIN
		COMMIT TRANSACTION
		RETURN 0	--Thành công
	END
END
